baseURL = "https://bizumatica.github.io/bizumatica-blog/"
languageCode = "pt-br"
title = "Bizumática Blog"
theme = "terminal"  # (O Hugo precisa saber qual tema usar)
publishDir = "docs"

# Canonify ajuda o Hugo a montar os links completos com o subdiretório
canonifyURLs = true
relativeURLs = false

[params]
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  animatedTheme = true
  customCSS = ["css/extended.css"]

[params.Logo]
  logoText = "Bizumática-Blog"

[pagination]
  pagerSize = 5

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts/"
  [[menu.main]]
    identifier = "home-return"
    name = "<< Voltar para Bizumática"
    url = "https://bizumatica.github.io/"
    weight = -10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Necessário para os boxes de Bizu e KaTeX