# --- Configuração de Staging (Teste) ---
baseURL = "https://bizumatica.github.io/bizumatica-blog/"
languageCode = "pt-br"
title = "Bizumatica-Blog"
theme = "terminal"
enableEmoji = true
publishDir = "docs"

# [Params] - Cores e estilo
[params]
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  animatedTheme = true

[params.Logo]
  logoText = "Bizumática-Blog"

# [Pagination]
[pagination]
  pagerSize = 5

# [Menu] - Navegação
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "home-return"
    name = "<< Voltar para Bizumática"
    url = "https://bizumatica.github.io/"
    weight = -10

# [Markup] - Permite HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true